# The application's default language. This is the language
# used if no language is specific by the application user.
# This also defines the language used for the text search.
default_locale_name: fr

# The set of languages supported by the applications.
available_locale_names:
- en
- fr
- de

# Default values for the admin interface's maps.
formalchemy_default_lat: 5860000
formalchemy_default_lon: 740000
formalchemy_default_zoom: 10

# The list of functionalities that can be configured
# through the admin interface.
formalchemy_available_functionalities:
- default_basemap
- print_template
- mapserver_substitution

# Functionalities that are accessible to anonymous
# users.
anonymous_functionalities:
  print_template:
  - 1 A4 portrait
  - 2 A3 landscape

# Functionalities that are accessible to authenticated
# users with no associated functionalities in the
# database.
registered_functionalities: {}

# Currently unused. To be removed.
webclient_array_functionalities:
webclient_string_functionalities:
- default_basemap

# Define URLs to the parent application. Only useful is
# this application is a child application in a parent/child
# architecture.
external_themes_url:
external_mapserv_url:

# The "raster web services" configuration. See the "raster"
# chapter in the integrator documentation.
raster:
