language: python
python:
- 2.6
- 2.7

services:
- postgresql

env:
  global:
  - secure: "UxpVOfQ9oePIcgRqsFzuVvpcng/syX6snuqw01XjK/3dWwyjhehBL17Yfzsn8NAgsiEdJ7SiTOhb3cfiHNHNX0mzfojPtvcFcGDmHGfH5nIufsGubeck6CErKHFT0uAhJywfPSgi53n0RteiIJAKc0bzaYzoMRG7RUPsvk3HRnE="
  matrix:
  - POSTGIS_VERSION=1.5 MAPSERVER_VERSION=6.0 BUILDOUT_CFG=buildout_travis_ms6.cfg PKG_INSTALL="cgi-mapserver=6.0.1-2ubuntu1.1 postgresql-9.1-postgis=1.5.3-2 postgis=1.5.3-2"
  - POSTGIS_VERSION=2.1 MAPSERVER_VERSION=6.0 BUILDOUT_CFG=buildout_travis_ms6.cfg PKG_INSTALL="cgi-mapserver=6.0.1-2ubuntu1.1"
  - POSTGIS_VERSION=1.5 MAPSERVER_VERSION=7.0 BUILDOUT_CFG=buildout_travis.cfg APT_REPO=ppa:stephane-brunner/precise PKG_INSTALL="cgi-mapserver postgresql-9.1-postgis=1.5.3-2 postgis=1.5.3-2"
  - POSTGIS_VERSION=2.0 MAPSERVER_VERSION=7.0 BUILDOUT_CFG=buildout_travis.cfg APT_REPO=ppa:stephane-brunner/precise-gis PKG_INSTALL="cgi-mapserver postgis=2.0.3-2~precise4 postgresql-9.1-postgis-2.0=2.0.3-2~precise4 postgresql-9.1-postgis-2.0-scripts=2.0.3-2~precise4"

before_install:
- cat /etc/apt/sources.list.d/*
- sudo apt-get install -y --force-yes apache2 aptitude
- if [[ "$APT_REPO" != "" ]]; then sudo add-apt-repository -y $APT_REPO; fi
- sudo apt-get update
- if [[ "$PKG_INSTALL" != "" ]]; then sudo aptitude install -y $PKG_INSTALL; fi
- dpkg -l|grep postgis
- sudo -u postgres psql --version

- sudo -u postgres createdb -E UTF8 -T template0 c2cgeoportal_test
- if [[ "$POSTGIS_VERSION" != "2.1" ]]; then psql -d c2cgeoportal_test -U postgres -f /usr/share/postgresql/9.1/contrib/postgis-$POSTGIS_VERSION/postgis.sql > /dev/null; fi
- if [[ "$POSTGIS_VERSION" != "2.1" ]]; then psql -d c2cgeoportal_test -U postgres -f /usr/share/postgresql/9.1/contrib/postgis-$POSTGIS_VERSION/spatial_ref_sys.sql > /dev/null; fi
- if [[ "$POSTGIS_VERSION" == "2.1" ]]; then psql -d c2cgeoportal_test -U postgres -c "CREATE EXTENSION postgis;"; fi
- if [[ "$MAPSERVER_VERSION-$POSTGIS_VERSION" == "6.0-2.1" ]]; then psql -d c2cgeoportal_test -U postgres -f /usr/share/postgresql/9.1/contrib/postgis-$POSTGIS_VERSION/legacy_minimal.sql; fi

- sudo -u postgres createuser www-data --no-superuser --no-createdb --no-createrole
- sudo -u postgres psql -q -d c2cgeoportal_test -f travis/db.sql

install:
- python bootstrap.py --version 1.5.2 --distribute --download-base http://pypi.camptocamp.net/distribute-0.6.22_fix-issue-227/ --setup-source http://pypi.camptocamp.net/distribute-0.6.22_fix-issue-227/distribute_setup.py
- buildout/bin/buildout -c $BUILDOUT_CFG
- buildout/bin/pip install -r dev-requirements.txt --trusted-host pypi.camptocamp.net
- sudo /usr/sbin/apache2ctl graceful

before_script:
- cd doc
- virtualenv --no-site-packages --distribute env
- source env/bin/activate
- pip install -r requirements.txt
- cd -

script: 
- travis/doc.sh
- buildout/bin/flake8 --version
- find c2cgeoportal/*.py c2cgeoportal/lib c2cgeoportal/scripts c2cgeoportal/views -name \*.py | xargs ./buildout/bin/flake8 --ignore=E712 --max-complexity=20 --max-line-length=100
- find c2cgeoportal/*.py c2cgeoportal/tests -name \*.py | xargs ./buildout/bin/flake8 --ignore=E501
- buildout/bin/pcreate -s c2cgeoportal_create /tmp/test package=test srid=21781 mobile_application_title="Mobile App" > /dev/null
- buildout/bin/pcreate -s c2cgeoportal_update /tmp/test package=test > /dev/null
- buildout/bin/alembic -c c2cgeoportal/tests/functional/alembic.ini upgrade head
- buildout/bin/alembic -c c2cgeoportal/tests/functional/alembic.ini downgrade base
- rm -rf /tmp/test
- buildout/bin/python setup.py nosetests --stop --nocapture --nologcapture

after_failure:
- buildout/bin/python setup.py nosetests

after_success:
- travis/deploy.sh
- pip install coveralls
- coveralls

notifications:
  email:
    on_failure: change
