dist: trusty
sudo: required

language: python
python:
- "3.6"

service:
- docker

env:
  global:
    - secure: aZWcHZWV8lN2SNU2fcUsG8+fVQLOxwDUFYDvuftZALebRG2AHINTkbS31sKbeSwS19ZYpjcuVOKC9HxNAlnMxsdO1NvvFEbSJJD/yqq0V4EfTRqptZYsFCUou0eXIUWEnoFHD1nY3NhuPQjDoad995xU92z0BzwduxUAj28liu4=

before_install:
- pip install --disable-pip-version-check --no-cache-dir --requirement travis/requirements.txt
- docker build --tag=external-db docker/test-external-db
- |
  if [ "${TX_PASS}" != "" ]
  then
  echo "[https://www.transifex.com]" >> ~/.transifexrc
  echo "hostname = https://www.transifex.com" >> ~/.transifexrc
  echo "username = stephane.brunner@camptocamp.com" >> ~/.transifexrc
  echo "password = ${TX_PASS}" >> ~/.transifexrc
  echo "token =" >> ~/.transifexrc
  fi
- mkdir /tmp/travis
- >
  travis/docker-get
  --tag camptocamp/geomapfish_build_dev:latest
  --folder docker/build
  --paths docker/build
- >
  travis/docker-get
  --tag camptocamp/geomapfish_build:latest
  --folder .
  --rules transifex-get buildlocales c2cgeoportal/scaffolds/update/CONST_create_template/
  --paths docker/build setup.py README.rst c2cgeoportal/ docker/build/fixversions.txt
- |
    [[ `./docker-run id` =~ uid=[0-9]+\(travis\)\ gid=[0-9]+\(geomapfish\)\ groups=[0-9]+\(geomapfish\) ]]

install:
- if [ ${TRAVIS_PULL_REQUEST} != "false" ] ; then git fetch origin ${TRAVIS_BRANCH}:${TRAVIS_BRANCH}; fi
- ./docker-run travis/no-make-error.sh help
- ./docker-run make -f travis.mk build
- travis/create-new-project.sh
- travis/test-upgrade.sh
- travis/run-on.sh /tmp/travis/testgeomapfish/ ./docker-run make -f travis.mk build project.yaml

script:
- docker version
- docker-compose --version

# Test return code
- ./docker-run travis/test-eof-newline
- ./docker-compose-run true
- |
    if ./docker-compose-run false
    then
        false
    fi

# Test new project
- >
  travis/run-on.sh /tmp/travis/testgeomapfish/
  ./docker-run pcreate
  --scaffold=c2cgeoportal_update
  --ignore-conflicting-name
  --overwrite /tmp/travis/testgeomapfish > /dev/null
  # on upgrade - do not add any argument on this command
- travis/run-on.sh /tmp/travis/testgeomapfish/ ./docker-run make -f travis.mk checks
- >
  travis/run-on.sh /tmp/travis/testgeomapfish/
  find setup.py testgeomapfish/*.py testgeomapfish/views -name \*.py | xargs travis/quote
- travis/run-on.sh /tmp/travis/testgeomapfish/ docker-compose up -d
- travis/waitwsgi http://localhost:8080/
- travis/test-new-project check_collector
- travis/test-new-project check_collector?type=all
- travis/test-new-project layers/test/values/type enum
- travis/run-on.sh /tmp/travis/testgeomapfish/ docker-compose logs
- travis/run-on.sh /tmp/travis/testgeomapfish/ docker-compose down
- travis/run-on.sh /tmp/travis/testgeomapfish/ ./docker-run travis/status.sh
- travis/run-on.sh /tmp/travis/testgeomapfish/ ./docker-run travis/empty-make.sh -f travis.mk build
- travis/run-on.sh /tmp/travis/testgeomapfish/ ./docker-run make -f empty-vars.mk config.yaml
- ./docker-compose-run alembic --config tests/functional/alembic.ini upgrade head
- ./docker-compose-run alembic --config tests/functional/alembic_static.ini upgrade head
- ./docker-compose-run alembic --config tests/functional/alembic_static.ini downgrade base
- ./docker-compose-run alembic --config tests/functional/alembic.ini downgrade base

# Test c2cgeoportal
- ./docker-run travis/empty-make.sh -f travis.mk build
- ./docker-run travis/no-make-error.sh -f travis.mk help
- ./docker-run make -f travis.mk doc
- ./docker-run make -f travis.mk checks
- ./docker-run make -f travis.mk tests/functional/alembic.ini
- ./docker-compose-run alembic --config tests/functional/alembic.ini upgrade head
- ./docker-compose-run alembic --config tests/functional/alembic_static.ini upgrade head
- ./docker-compose-run nosetests

after_success:
- ./docker-run coveralls
- export CODACY_PROJECT_TOKEN=1605f78ffb214af5ba6cb172a95db5d1
- ./docker-run python-codacy-coverage -r coverage.xml
- openssl aes-256-cbc -K $encrypted_ae821512cabf_key -iv $encrypted_ae821512cabf_iv -in deploy_key.enc -out ~/.ssh/id_rsa -d | true
- chmod 600 ~/.ssh/id_rsa
- git config --global user.email travis@camptocamp.com
- git config --global user.name Travis
- git remote set-url origin git@github.com:camptocamp/c2cgeoportal.git
- GIT_REV=`git log | head --lines=1 | awk '{{print $2}}'`
- |
  if [ "${TRAVIS_REPO_SLUG}-${TRAVIS_PULL_REQUEST}" == camptocamp/c2cgeoportal-false ]
  then
    travis/doc.sh
  fi

before_deploy:
- git checkout ${GIT_REV}
- if [[ ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\..+$ ]] ; then
  sed --expression 's/REQUIREMENTS [\?]= c2cgeoportal/REQUIREMENTS ?= c2cgeoportal=='"${TRAVIS_TAG}"'/g' --in-place c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl;
  sed --expression 's/version="[0-9]\+\.[0-9]\+",/version="'"${TRAVIS_TAG}"'",/g' --in-place setup.py;
  git diff;
  fi

deploy:
- provider: pypi
  user: sbrunner
  password:
    secure: dT4Z3Zk2SGq1BPl+mX2iI0ubK7veSPb1b0fGrKHpvC3gBxuGUDMhtHw5dgopdWWeUhZLzLoPpEZPyCHtJhE2vunGwZfmJXkrqp/yC1meszZpDgBkpRWzx62u/f1+FmUdGPukvlqTfzgl/vJwertPRzX9Y4hanoFIDQvIKnp37Ls=
  skip_cleanup: true
  skip_upload_docs: true
  distributions: sdist bdist_wheel
  on:
    repo: camptocamp/c2cgeoportal
    tags: true
    condition: '"${TRAVIS_TAG}" =~ ^[0-9]+\.[0-9]+\..+$'
- provider: script
  script: ./docker-run make transifex-send
  skip_cleanup: true
  on:
    repo: camptocamp/c2cgeoportal
    branch: master
    condition: '"${TRAVIS_PULL_REQUEST}" = false'
- provider: script
  script: travis/doc.sh
  skip_cleanup: true
  on:
    repo: camptocamp/c2cgeoportal
    branch: master
    condition: '"${TRAVIS_PULL_REQUEST}" = false'

notifications:
  email:
    on_failure: change
