dist: precise
language: python

python:
- 2.6
- 2.7

env:
  global:
  - secure: "UxpVOfQ9oePIcgRqsFzuVvpcng/syX6snuqw01XjK/3dWwyjhehBL17Yfzsn8NAgsiEdJ7SiTOhb3cfiHNHNX0mzfojPtvcFcGDmHGfH5nIufsGubeck6CErKHFT0uAhJywfPSgi53n0RteiIJAKc0bzaYzoMRG7RUPsvk3HRnE="

before_install:
- git fetch
- cat /etc/apt/sources.list.d/*
- sudo apt-get install -y --force-yes aptitude
- sudo apt-get update
- sudo aptitude install -y deploy

install:
- make -f travis.mk c2c-egg
- make -f travis.mk build

script:
- if [ ${TRAVIS_PULL_REQUEST} != "false" ] ; then git fetch origin ${TRAVIS_BRANCH}:${TRAVIS_BRANCH}; fi
- if [ ${TRAVIS_PULL_REQUEST} != "false" ] ; then git diff --check ${TRAVIS_BRANCH} -- ; fi
- make -f travis.mk doc
- travis/quote `find c2cgeoportal/lib c2cgeoportal/scaffolds c2cgeoportal/templates c2cgeoportal/tests c2cgeoportal/views -name '*.py'` c2cgeoportal/*.py setup.py
- git checkout c2cgeoportal/locale/*/LC_MESSAGES/c2cgeoportal.po
- travis/status.sh
# verify c2cgeoportal version
- if [[ ${TRAVIS_TAG} =~ ^[0-9]+.[0-9]+.[0-9]+(dev[0-9]+|rc[0-9]|\.[0-9]+)?$ ]] ; then test `grep c2cgeoportal== c2cgeoportal/scaffolds/update/CONST_requirements.txt|awk -F '==' '{{print $2}}'` = ${TRAVIS_TAG} ; fi
- if [[ ${TRAVIS_TAG} =~ ^[0-9]+.[0-9]+.[0-9]+(dev[0-9]+|rc[0-9]|\.[0-9]+)?$ ]] ; then test `grep c2cgeoportal-win== c2cgeoportal/scaffolds/update/CONST_requirements_windows.txt|awk -F '==' '{{print $2}}'` = ${TRAVIS_TAG} ; fi
- if [[ ${TRAVIS_TAG} =~ ^[0-9]+.[0-9]+.[0-9]+(dev[0-9]+|rc[0-9]|\.[0-9]+)?$ ]] ; then test `python setup.py --version` = ${TRAVIS_TAG} ; fi

after_success:
- travis/deploy.sh
- travis/pip.sh install coveralls
- .build/venv/bin/coveralls

notifications:
  email:
    on_failure: change
